=== KRHero03/College_Labwork/3rd_Year/ITA/Assignment2/emails.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema  targetNamespace="http://www.w3schools.com/"
elementFormDefault="qualified"
xmlns="http://www.w3schools.com emails.xsd"
xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="emails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="email" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="to" type="xs:string" minOccurs="1" />
                            <xs:element name="from" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:element name="heading" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:element name="body" type="xs:string" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KRHero03/College_Labwork/3rd_Year/ITA/Assignment2/emails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE emails SYSTEM "./emails.dtd">
<!-- <emails 
xmlns="http://www.w3schools.com/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:schemaLocation="http://www.w3schools.com emails.xsd"> -->
<emails>
    <email>
        <to>Vimal</to>
        <from>Sonoo</from>
        <heading>Hello</heading>
        <body>Hello brother, how are you!</body>
    </email>
    <email>
        <to>Peter</to>
        <from>Jack</from>
        <heading>Birth day wish</heading>
        <body>Happy birth day Tom!</body>
    </email>
</emails>
